var allCountries = [
  ["Afghanistan (‫افغانستان‬‎)", "af", "93", "+..-..-...-....", "Regions", "ZONES"],
  ["Åland Islands", "ax", "358", "", "ZONINGNAME", "ZONES"],
  ["American Samoa", "as", "1684", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["Anguilla", "ai", "1264", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["Antarctica", "aq", "672", "", "ZONINGNAME", "ZONES"],
  ["Aruba", "aw", "297", "+...-...-....", "ZONINGNAME", "ZONES"],
  ["Bermuda", "bm", "1441", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["Bouvet Island", "bv", "47", "", "ZONINGNAME", "ZONES"],
  ["British Indian Ocean Territory", "io", "246", "+...-...-....", "ZONINGNAME", "ZONES"],
  ["British Virgin Islands", "vg", "1284", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["Caribbean Netherlands", "bq", "599", "+...-...-....", 1, "ZONINGNAME", "ZONES"],
  ["Cayman Islands", "ky", "1345", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["Christmas Island", "cx", "61", "", "ZONINGNAME", "ZONES"],
  ["Cocos (Keeling) Islands", "cc", "61", "", "ZONINGNAME", "ZONES"],
  ["Cook Islands", "ck", "682", "+...-..-...", "ZONINGNAME", "ZONES"],
  ["Falkland Islands (Islas Malvinas)", "fk", "500", "+...-.....", "ZONINGNAME", "ZONES"],
  ["Faroe Islands (Føroyar)", "fo", "298", "+...-...-...", "ZONINGNAME", "ZONES"],
  ["French Guiana (Guyane française)", "gf", "594", "+...-.....-....", "ZONINGNAME", "ZONES"],
  ["French Polynesia (Polynésie française)", "pf", "689", "+...-..-..-..", "ZONINGNAME", "ZONES"],
  ["French Southern and Antarctic Lands", "tf", "262", "", "ZONINGNAME", "ZONES"],
  ["Gibraltar", "gi", "350", "+...-...-.....", "ZONINGNAME", "ZONES"],
  ["Greenland (Kalaallit Nunaat)", "gl", "299", "+...-..-..-..", "ZONINGNAME", "ZONES"],
  ["Guadeloupe", "gp", "590", "", 0, "ZONINGNAME", "ZONES"],
  ["Guam", "gu", "1671", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["Guernsey", "gg", "44", "", "ZONINGNAME", "ZONES"],
  ["Heard Island and McDonald Islands", "hm", "672", "", "ZONINGNAME", "ZONES"],
  ["Hong Kong (香港)", "hk", "852", "+... .... ....", "ZONINGNAME", "ZONES"],
  ["Isle of Man", "im", "44", "", "ZONINGNAME", "ZONES"],
  ["Jersey", "je", "44", "", "ZONINGNAME", "ZONES"],
  ["Macau (澳門)", "mo", "853", "+...-....-....", "ZONINGNAME", "ZONES"],
  ["Martinique", "mq", "596", "+...(...)..-..-..", "ZONINGNAME", "ZONES"],
  ["Mayotte", "yt", "262", "", "ZONINGNAME", "ZONES"],
  ["Montserrat", "ms", "1664", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["New Caledonia (Nouvelle-Calédonie)", "nc", "687", "+...-..-....", "ZONINGNAME", "ZONES"],
  ["Niue", "nu", "683", "+...-....", "ZONINGNAME", "ZONES"],
  ["Norfolk Island", "nf", "672", "+...-...-...", "ZONINGNAME", "ZONES"],
  ["Northern Mariana Islands", "mp", "1670", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["Pitcairn Islands", "pn", "64", "", "ZONINGNAME", "ZONES"],
  ["Réunion (La Réunion)", "re", "262", "+...-.....-....", "ZONINGNAME", "ZONES"],
  ["Saint Barthélemy (Saint-Barthélemy)", "bl", "590", "", 1, "ZONINGNAME", "ZONES"],
  ["Saint Helena", "sh", "290", "ZONINGNAME", "ZONES"],
  ["Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)", "pm", "508", "ZONINGNAME", "ZONES"],
  ["Sint Maarten", "sx", "1721", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["South Georgia and the South Sandwich Islands", "gs", "500", "", "ZONINGNAME", "ZONES"],
  ["Svalbard and Jan Mayen", "sj", "47", "", "ZONINGNAME", "ZONES"],
  ["Swaziland", "sz", "268", "+...-..-..-....", "ZONINGNAME", "ZONES"],
  ["Tokelau", "tk", "690", "+...-....", "ZONINGNAME", "ZONES"],
  ["Turks and Caicos Islands", "tc", "1649", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["U.S. Virgin Islands", "vi", "1340", "+.(...)...-....", "ZONINGNAME", "ZONES"],
  ["United States Minor Outlying Islands", "um", "1", "", 2, "ZONINGNAME", "ZONES"],
];
